services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  R3H6\WebTestCase\:
    resource: '../Classes/*'

  R3H6\WebTestCase\EventListener\RedirectResponseHandler:
    tags:
      - name: event.listener
