#!/bin/bash

## Description: Create db dump for development
## Usage: dbdump
## Example: "ddev dbdump"

DUMP=Build/Data/db.sql

rm -f $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables be_groups >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables be_users >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables fe_groups >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables fe_users >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables pages >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables sys_news >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables sys_template >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables tt_content >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --tables sys_file >> $DUMP
mysqldump db --compact --skip-extended-insert --add-drop-table --no-set-names --where="deleted=0" --tables sys_file_reference >> $DUMP
