#!/bin/bash

export typo3DatabaseName=db
export typo3DatabaseHost=db
export typo3DatabaseUsername=root
export typo3DatabasePassword=root
export typo3DatabasePort=3306
export typo3DatabaseDriver=mysqli

#export typo3DatabaseDriver=pdo_sqlite
.Build/bin/phpunit -c .Build/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml tests/Functional "$@"
